name: Build and Push Docker Images

on:
  push:
    branches:
      - 'main'
    paths:
      - 'cart/**'
      - 'catalogue/**'
      - 'dispatch/**'
      - 'payment/**'
      - 'ratings/**'
      - 'user/**'
      - 'web/**'
      - 'mongo/**'
      - 'mysql/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - cart
          - catalogue
          - dispatch
          - payment
          - ratings
          - user
          - web
          - mongo
          - mysql

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensure that it fetches the last 2 commits for git diff

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Determine if ${{ matrix.service }} service was modified
        id: check_changes
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "run_${{ matrix.service }}=true" >> $GITHUB_ENV
          elif git diff --name-only HEAD^ HEAD | grep -q '^${{ matrix.service }}/'; then
            echo "run_${{ matrix.service }}=true" >> $GITHUB_ENV
          else
            echo "run_${{ matrix.service }}=false" >> $GITHUB_ENV
          fi

      - name: Build and push ${{ matrix.service }} Docker image
        if: env.run_${{ matrix.service }} == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: palakuws/robo-shop:${{ matrix.service }}-latest
