name: Pipeline for creating Docker images for cart and catalogue

on:
  push:
    branches:
      - 'main'
    paths:
      - 'cart/**'
      - 'catalogue/**'
  workflow_dispatch: # For manual trigger

jobs:
  cart_service:
    name: CI service for cart service
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && 'cart/' in github.event.head_commit.modified)
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show working directory and files
        run: |
          pwd
          ls -lart

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: palakuws/robo-shop:cart-latest
          context: ./cart
          file: ./cart/Dockerfile

  catalogue_service:
    name: CI service for catalogue service
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && 'catalogue/' in github.event.head_commit.modified)
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show working directory and files
        run: |
          pwd
          ls -lart

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: palakuws/robo-shop:catalogue-latest
          context: ./catalogue
          file: ./catalogue/Dockerfile
