name: Build and Push Docker Images

on:
  push:
    branches:
      - 'main'
    paths:
      - 'cart/**'
      - 'catalogue/**'
      - 'dispatch/**'
      - 'payment/**'
      - 'ratings/**'
      - 'user/**'
      - 'web/**'
      - 'mongo/**'
      - 'mysql/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - cart
          - catalogue
          - dispatch
          - payment
          - ratings
          - user
          - web
          - mongo
          - mysql

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Determine if ${{ matrix.service }} service was modified
        id: check_changes
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "run_service=true" >> $GITHUB_ENV
          else
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^${{ matrix.service }}/"
            if [ $? -eq 0 ]; then
              echo "run_service=true" >> $GITHUB_ENV
            else
              echo "run_service=false" >> $GITHUB_ENV
            fi
          fi

      - name: Build and push ${{ matrix.service }} Docker image
        if: env.run_service == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: palakuws/robo-shop:${{ matrix.service }}-latest
