name: Pipeline for creating Docker images

on:
  push:
    branches:
      - 'main'
    paths:
      - 'cart/**'
      - 'catalogue/**'
  workflow_dispatch: # For manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Universal Checkout Step
      - name: Checkout Code
        uses: actions/checkout@v3

      # Universal Docker Login Step
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKER_KEY }}

      # Cart Service
      - name: Determine if cart service was modified
        id: check_cart_changes
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "run_cart=true" >> $GITHUB_ENV
          elif git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^cart/'; then
            echo "run_cart=true" >> $GITHUB_ENV
          else
            echo "run_cart=false" >> $GITHUB_ENV
          fi

      - name: Build and push Cart Docker image
        if: env.run_cart == 'true'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: palakuws/robo-shop:cart-latest
          context: ./cart
          file: ./cart/Dockerfile

      # Catalogue Service
      - name: Determine if catalogue service was modified
        id: check_catalogue_changes
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "run_catalogue=true" >> $GITHUB_ENV
          elif git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^catalogue/'; then
            echo "run_catalogue=true" >> $GITHUB_ENV
          else
            echo "run_catalogue=false" >> $GITHUB_ENV
          fi

      - name: Build and push Catalogue Docker image
        if: env.run_catalogue == 'true'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: palakuws/robo-shop:catalogue-latest
          context: ./catalogue
          file: ./catalogue/Dockerfile
